// This file is auto-generated by @hey-api/openapi-ts

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const ComponentItemPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        component_type: {
            type: 'string',
            maxLength: 255,
            title: 'Component Type'
        },
        provider: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Provider'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1024
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        role_summary: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1024
                },
                {
                    type: 'null'
                }
            ],
            title: 'Role Summary'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        diagram_version_id: {
            type: 'string',
            format: 'uuid',
            title: 'Diagram Version Id'
        }
    },
    type: 'object',
    required: ['name', 'component_type', 'id', 'diagram_version_id'],
    title: 'ComponentItemPublic'
} as const;

export const DiagramEdgeCreateSchema = {
    properties: {
        source_node_id: {
            type: 'string',
            format: 'uuid',
            title: 'Source Node Id'
        },
        target_node_id: {
            type: 'string',
            format: 'uuid',
            title: 'Target Node Id'
        },
        label: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Label'
        },
        metadata_json: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Metadata Json'
        }
    },
    type: 'object',
    required: ['source_node_id', 'target_node_id'],
    title: 'DiagramEdgeCreate'
} as const;

export const DiagramEdgePublicSchema = {
    properties: {
        source_node_id: {
            type: 'string',
            format: 'uuid',
            title: 'Source Node Id'
        },
        target_node_id: {
            type: 'string',
            format: 'uuid',
            title: 'Target Node Id'
        },
        label: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Label'
        },
        metadata_json: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Metadata Json'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        diagram_version_id: {
            type: 'string',
            format: 'uuid',
            title: 'Diagram Version Id'
        }
    },
    type: 'object',
    required: ['source_node_id', 'target_node_id', 'id', 'diagram_version_id'],
    title: 'DiagramEdgePublic'
} as const;

export const DiagramEdgeUpdateSchema = {
    properties: {
        label: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Label'
        },
        metadata_json: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Metadata Json'
        }
    },
    type: 'object',
    title: 'DiagramEdgeUpdate'
} as const;

export const DiagramJsonUpdateSchema = {
    properties: {
        diagram_json: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Diagram Json'
        },
        layout_json: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Layout Json'
        },
        notes_markdown: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes Markdown'
        }
    },
    type: 'object',
    title: 'DiagramJsonUpdate'
} as const;

export const DiagramNodeCreateSchema = {
    properties: {
        label: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Label'
        },
        node_type: {
            type: 'string',
            maxLength: 255,
            title: 'Node Type'
        },
        provider: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Provider'
        },
        metadata_json: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Metadata Json'
        },
        x_position: {
            type: 'number',
            title: 'X Position',
            default: 0
        },
        y_position: {
            type: 'number',
            title: 'Y Position',
            default: 0
        }
    },
    type: 'object',
    required: ['label', 'node_type'],
    title: 'DiagramNodeCreate'
} as const;

export const DiagramNodePublicSchema = {
    properties: {
        label: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Label'
        },
        node_type: {
            type: 'string',
            maxLength: 255,
            title: 'Node Type'
        },
        provider: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Provider'
        },
        metadata_json: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Metadata Json'
        },
        x_position: {
            type: 'number',
            title: 'X Position',
            default: 0
        },
        y_position: {
            type: 'number',
            title: 'Y Position',
            default: 0
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        diagram_version_id: {
            type: 'string',
            format: 'uuid',
            title: 'Diagram Version Id'
        }
    },
    type: 'object',
    required: ['label', 'node_type', 'id', 'diagram_version_id'],
    title: 'DiagramNodePublic'
} as const;

export const DiagramNodeUpdateSchema = {
    properties: {
        label: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Label'
        },
        node_type: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Node Type'
        },
        provider: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Provider'
        },
        metadata_json: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Metadata Json'
        },
        x_position: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'X Position'
        },
        y_position: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Y Position'
        }
    },
    type: 'object',
    title: 'DiagramNodeUpdate'
} as const;

export const DiagramVersionPublicSchema = {
    properties: {
        version_number: {
            type: 'integer',
            title: 'Version Number',
            default: 1
        },
        diagram_json: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Diagram Json'
        },
        layout_json: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Layout Json'
        },
        notes_markdown: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes Markdown'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        project_id: {
            type: 'string',
            format: 'uuid',
            title: 'Project Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'project_id'],
    title: 'DiagramVersionPublic'
} as const;

export const DiagramVersionsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/DiagramVersionPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'DiagramVersionsPublic'
} as const;

export const GenerationRequestSchema = {
    properties: {
        prompt: {
            type: 'string',
            maxLength: 4096,
            minLength: 1,
            title: 'Prompt'
        },
        cloud_context: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cloud Context'
        },
        diagram_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Diagram Type'
        }
    },
    type: 'object',
    required: ['prompt'],
    title: 'GenerationRequest'
} as const;

export const GenerationResultSchema = {
    properties: {
        diagram_version: {
            '$ref': '#/components/schemas/DiagramVersionPublic'
        },
        nodes: {
            items: {
                '$ref': '#/components/schemas/DiagramNodePublic'
            },
            type: 'array',
            title: 'Nodes'
        },
        edges: {
            items: {
                '$ref': '#/components/schemas/DiagramEdgePublic'
            },
            type: 'array',
            title: 'Edges'
        },
        components: {
            items: {
                '$ref': '#/components/schemas/ComponentItemPublic'
            },
            type: 'array',
            title: 'Components'
        },
        notes_markdown: {
            type: 'string',
            title: 'Notes Markdown'
        }
    },
    type: 'object',
    required: ['diagram_version', 'nodes', 'edges', 'components', 'notes_markdown'],
    title: 'GenerationResult'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ItemCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ItemCreate'
} as const;

export const ItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['title', 'id', 'owner_id'],
    title: 'ItemPublic'
} as const;

export const ItemUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ItemUpdate'
} as const;

export const ItemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ItemsPublic'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const ProjectCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1024
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        current_prompt: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 4096
                },
                {
                    type: 'null'
                }
            ],
            title: 'Current Prompt'
        },
        cloud_context: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cloud Context'
        },
        diagram_type: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Diagram Type'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ProjectCreate'
} as const;

export const ProjectPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1024
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        current_prompt: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 4096
                },
                {
                    type: 'null'
                }
            ],
            title: 'Current Prompt'
        },
        cloud_context: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cloud Context'
        },
        diagram_type: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Diagram Type'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['title', 'id', 'owner_id'],
    title: 'ProjectPublic'
} as const;

export const ProjectUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1024
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        current_prompt: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 4096
                },
                {
                    type: 'null'
                }
            ],
            title: 'Current Prompt'
        },
        cloud_context: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cloud Context'
        },
        diagram_type: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Diagram Type'
        }
    },
    type: 'object',
    title: 'ProjectUpdate'
} as const;

export const ProjectsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ProjectPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ProjectsPublic'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;