// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type ComponentItemPublic = {
    name: string;
    component_type: string;
    provider?: (string | null);
    description?: (string | null);
    role_summary?: (string | null);
    id: string;
    diagram_version_id: string;
};

export type DiagramEdgeCreate = {
    source_node_id: string;
    target_node_id: string;
    label?: (string | null);
    metadata_json?: (string | null);
};

export type DiagramEdgePublic = {
    source_node_id: string;
    target_node_id: string;
    label?: (string | null);
    metadata_json?: (string | null);
    id: string;
    diagram_version_id: string;
};

export type DiagramEdgeUpdate = {
    label?: (string | null);
    metadata_json?: (string | null);
};

export type DiagramJsonUpdate = {
    diagram_json?: (string | null);
    layout_json?: (string | null);
    notes_markdown?: (string | null);
};

export type DiagramNodeCreate = {
    label: string;
    node_type: string;
    provider?: (string | null);
    metadata_json?: (string | null);
    x_position?: number;
    y_position?: number;
};

export type DiagramNodePublic = {
    label: string;
    node_type: string;
    provider?: (string | null);
    metadata_json?: (string | null);
    x_position?: number;
    y_position?: number;
    id: string;
    diagram_version_id: string;
};

export type DiagramNodeUpdate = {
    label?: (string | null);
    node_type?: (string | null);
    provider?: (string | null);
    metadata_json?: (string | null);
    x_position?: (number | null);
    y_position?: (number | null);
};

export type DiagramVersionPublic = {
    version_number?: number;
    diagram_json?: (string | null);
    layout_json?: (string | null);
    notes_markdown?: (string | null);
    id: string;
    project_id: string;
    created_at?: (string | null);
};

export type DiagramVersionsPublic = {
    data: Array<DiagramVersionPublic>;
    count: number;
};

export type GenerationRequest = {
    prompt: string;
    cloud_context?: (string | null);
    diagram_type?: (string | null);
};

export type GenerationResult = {
    diagram_version: DiagramVersionPublic;
    nodes: Array<DiagramNodePublic>;
    edges: Array<DiagramEdgePublic>;
    components: Array<ComponentItemPublic>;
    notes_markdown: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type ProjectCreate = {
    title: string;
    description?: (string | null);
    current_prompt?: (string | null);
    cloud_context?: (string | null);
    diagram_type?: (string | null);
};

export type ProjectPublic = {
    title: string;
    description?: (string | null);
    current_prompt?: (string | null);
    cloud_context?: (string | null);
    diagram_type?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type ProjectsPublic = {
    data: Array<ProjectPublic>;
    count: number;
};

export type ProjectUpdate = {
    title?: (string | null);
    description?: (string | null);
    current_prompt?: (string | null);
    cloud_context?: (string | null);
    diagram_type?: (string | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type ProjectsListProjectsData = {
    limit?: number;
    skip?: number;
};

export type ProjectsListProjectsResponse = (ProjectsPublic);

export type ProjectsCreateProjectData = {
    requestBody: ProjectCreate;
};

export type ProjectsCreateProjectResponse = (ProjectPublic);

export type ProjectsReadProjectData = {
    projectId: string;
};

export type ProjectsReadProjectResponse = (ProjectPublic);

export type ProjectsUpdateProjectData = {
    projectId: string;
    requestBody: ProjectUpdate;
};

export type ProjectsUpdateProjectResponse = (ProjectPublic);

export type ProjectsDeleteProjectData = {
    projectId: string;
};

export type ProjectsDeleteProjectResponse = (Message);

export type ProjectsDuplicateProjectData = {
    projectId: string;
};

export type ProjectsDuplicateProjectResponse = (ProjectPublic);

export type ProjectsGenerateDiagramData = {
    projectId: string;
    requestBody: GenerationRequest;
};

export type ProjectsGenerateDiagramResponse = (GenerationResult);

export type ProjectsRefineDiagramData = {
    projectId: string;
    requestBody: GenerationRequest;
};

export type ProjectsRefineDiagramResponse = (GenerationResult);

export type ProjectsRegenerateNotesData = {
    projectId: string;
};

export type ProjectsRegenerateNotesResponse = (Message);

export type ProjectsRegenerateComponentsData = {
    projectId: string;
};

export type ProjectsRegenerateComponentsResponse = (Array<ComponentItemPublic>);

export type ProjectsListVersionsData = {
    limit?: number;
    projectId: string;
    skip?: number;
};

export type ProjectsListVersionsResponse = (DiagramVersionsPublic);

export type ProjectsRestoreVersionData = {
    projectId: string;
    versionId: string;
};

export type ProjectsRestoreVersionResponse = (DiagramVersionPublic);

export type ProjectsUpdateDiagramJsonData = {
    projectId: string;
    requestBody: DiagramJsonUpdate;
};

export type ProjectsUpdateDiagramJsonResponse = (DiagramVersionPublic);

export type ProjectsAddNodeData = {
    projectId: string;
    requestBody: DiagramNodeCreate;
};

export type ProjectsAddNodeResponse = (DiagramNodePublic);

export type ProjectsUpdateNodeData = {
    nodeId: string;
    projectId: string;
    requestBody: DiagramNodeUpdate;
};

export type ProjectsUpdateNodeResponse = (DiagramNodePublic);

export type ProjectsDeleteNodeData = {
    nodeId: string;
    projectId: string;
};

export type ProjectsDeleteNodeResponse = (Message);

export type ProjectsAddEdgeData = {
    projectId: string;
    requestBody: DiagramEdgeCreate;
};

export type ProjectsAddEdgeResponse = (DiagramEdgePublic);

export type ProjectsUpdateEdgeData = {
    edgeId: string;
    projectId: string;
    requestBody: DiagramEdgeUpdate;
};

export type ProjectsUpdateEdgeResponse = (DiagramEdgePublic);

export type ProjectsDeleteEdgeData = {
    edgeId: string;
    projectId: string;
};

export type ProjectsDeleteEdgeResponse = (Message);

export type ProjectsExportMarkdownData = {
    projectId: string;
};

export type ProjectsExportMarkdownResponse = (unknown);

export type ProjectsExportPngData = {
    projectId: string;
};

export type ProjectsExportPngResponse = (unknown);

export type ProjectsExportSvgData = {
    projectId: string;
};

export type ProjectsExportSvgResponse = (unknown);

export type ProjectsExportBundleData = {
    projectId: string;
};

export type ProjectsExportBundleResponse = (unknown);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);